- hosts: servers
  tasks:
    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
      become: yes
  
    - name: Remove config file
      ansible.builtin.file:
        path: /home/{{ item }}/.gitconfig
        state: absent
      loop: "{{ users }}"
      become: yes